name: github
version: 5.2.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: A high-level GitHub API Client Library that uses Github's v3 API
homepage: https://github.com/DirectMyFile/github.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  http: '>=0.11.3 <0.13.0'
  http_parser: ^3.1.1
  json_annotation: '>=2.0.0 <4.0.0'
  meta: ^1.1.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  json_serializable: ^3.2.2
  mockito: ^3.0.0
  pedantic: ^1.0.0
  test: ^1.3.0

builders:
  json_serializable: ^3.2.2
